[package]
name = "ws-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
futures-channel = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.41.1", features = ["full", "sync"] }
tokio-tungstenite = "0.24.0"
tokio-util = "0.7.12"